feat: db upgrade
TheCodingDen/projects-bot pull request #12
Opened 2022-07-03 21:07 UTC by nullishamy

This upgrades the DB by changing to Postgres, implementing Prisma, and refactoring the DB implementation to comply with the above.

This will be used with Heroku's DB implementation to provide easy persistence whilst the project is hosted in production.

Closes #6

2022-07-07 02:33 UTC, MaxInertia reviewed
Suggestion to use custom type guard instead of type assertion

2022-07-07 02:33 UTC, MaxInertia commented on src/managers/submissions.ts
> +    const detailsNotNull = data as typeof data & { details: SubmissionDetails }
We could use a type guard instead. That way the check lives alongside the type refinement. and the intent is clear without requiring these comments.
```ts
function hasDetails<D, T extends {details: D | null}>(x: T): x is T & {details: NonNullable<T['details']>} {
  return x.details !== null
}
```
Then we replace this
```ts
if(!data.details) {
```
with this
```ts
if(!hasDetails(data)) {
```

and remove each instance of these five lines

2022-07-07 02:33 UTC, MaxInertia commented on src/managers/submissions.ts
> +      const detailsNotNull = d as typeof d & { details: SubmissionDetails }
ditto

2022-07-07 02:33 UTC, MaxInertia commented on src/managers/submissions.ts
> +    const detailsNotNull = data as typeof data & { details: SubmissionDetails }
ditto

2022-07-07 09:40 UTC, nullishamy commented on src/managers/submissions.ts
> +    const detailsNotNull = data as typeof data & { details: SubmissionDetails }
Thanks, that seems to work. Would you happen to know why it was unable to infer originally?

2022-07-08 00:56 UTC, BobobUnicorn requested changes

2022-07-08 00:56 UTC, BobobUnicorn commented on src/models/submission.ts
> +    ]
```
type Cross<T extends readonly unknown[], U extends readonly unknown[]> = Flatten<{
  [K in keyof T]: {
    [J in keyof U]: [T[K], U[J]]
  }
}>

type Flatten<T extends readonly unknown[], Acc extends readonly unknown[] = readonly []> = 
  T extends readonly [infer H, ...infer T] ?
    H extends readonly unknown[] ?
      Flatten<T, readonly [...Acc, ...H]> :
      Flatten<T, readonly [...Acc, H]> :
    Acc;

function crossProduct<T extends readonly unknown[], U extends readonly unknown[]>(a: readonly [...T], z: readonly [...U]): Cross<T, U> {
  return a.flatMap(aa => z.map(zz => [aa, zz])) as unknown as Cross<T, U>;
}

return crossProduct(['upvotes', 'downvotes'] as const, ['staff', 'veterans'] as const).flatMap(([a, b]) => votes[a][b]);
```

2022-07-08 02:18 UTC, MaxInertia commented on src/managers/submissions.ts
> +    const detailsNotNull = data as typeof data & { details: SubmissionDetails }
Nope. I was expecting the type to be refined just like in this case: [TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvARgQwE4C4oDOw2AlgHYDmUAPlGQK4A2jAvgLABQnAZvWQMbAScMlHoEI8OAApuCfFICU+IqUppOUKCW7SAhHLgA6LNkUaOWrdgjB62UQCJHmqOy6WoNuw6iGTOADcrgD0IVYRVgB6APyc7jx8gsKi4pIIAOokwAAWACo52HAA7rLysAjKhMTkVKiuOvr+pub1nlq5RcV0EN0AothF2NKOxZgA1uOYjoquCZ7e9qLNQaHhkRGx8ZxAA)

Do you know why @BobobUnicorn?

2022-07-08 02:34 UTC, BobobUnicorn commented on src/managers/submissions.ts
> +    const detailsNotNull = data as typeof data & { details: SubmissionDetails }
I explained it in voice chat, but essentially TypeScript won't propagate the implicit type guard/type narrowing from the type of the inner property to the outer type; `foo.bar` is no longer `null` but `foo` will still be `Foo`

2022-07-09 04:22 UTC, MaxInertia commented on src/managers/submissions.ts
> +    const detailsNotNull = data as typeof data & { details: SubmissionDetails }
For some reason I thought this was added in a recent TS version, but looking through them I don't see it.

2022-07-11 21:14 UTC, BobobUnicorn approved these changes

2022-07-11 21:15 UTC, merged