Adds an association between submissions and messages
TheCodingDen/projects-bot pull request #253
Opened 2021-07-18 15:51 UTC by Quozlet

When a project has gone through all checks and is being submitted, messages related to it are stored and then bulk deleted when approved or denied.

Closes #137

2021-11-14 13:38 UTC, linuswillner requested changes
One minor nit, otherwise LGTM.

2021-11-14 13:38 UTC, linuswillner commented on src/utils/processReaction.ts
> +      try { await (guild.channels.cache.get(projectSubmissionsChannelId) as TextChannel | undefined)?.bulkDelete(project.relatedMsgs) } catch (err) {
Pretty long line, I see the push for brevity, but I think clarity should be prioritised here.
```suggestion
      try {
      	await (guild.channels.cache.get(projectSubmissionsChannelId) as TextChannel | undefined)?.bulkDelete(project.relatedMsgs)
      } catch (err) {
```

2021-11-14 13:41 UTC, Quozlet commented on src/utils/processReaction.ts
> +      try { await (guild.channels.cache.get(projectSubmissionsChannelId) as TextChannel | undefined)?.bulkDelete(project.relatedMsgs) } catch (err) {
Agreed. I feel like I ran a formatter or something that generated that but 🤷

2021-11-15 07:22 UTC, linuswillner approved these changes

2021-11-15 07:22 UTC, merged