feat: slash command implementation
TheCodingDen/projects-bot pull request #301
Opened 2022-06-24 15:23 UTC by nullishamy

This starts the implementation of slash commands into the project. It adds a command manger and the ability to register commands with Discord. It has primitive wrapping of the d.js API but this is subject to improvement.

One command, edit, has been implemented with this PR. The formatting of commands is subject to change.

Finally, this upgrades the typescript version of the project.

Closes #281.

2022-06-27 22:18 UTC, BobobUnicorn requested changes

2022-06-27 22:18 UTC, BobobUnicorn commented on src/commands/edit.ts
> +      ephemeral: true
pls no ephemeral

2022-06-27 22:18 UTC, BobobUnicorn commented on src/commands/reject.ts
> +  { name: 'Inaccessable repository', value: 'inaccessable-repository' },
```suggestion
  { name: 'Inaccessible repository', value: 'inaccessible-repository' },
```

2022-06-27 22:18 UTC, BobobUnicorn commented on src/commands/reject.ts
> +        content: `Could not find corrosponding template for reason ${reasonName}, please report this.`
```suggestion
        content: `Could not find corresponding template for reason ${reasonName}, please report this.`
```

2022-06-27 22:18 UTC, BobobUnicorn commented on src/commands/reject.ts
> +        type: 'GUILD_PUBLIC_THREAD',
set to private

2022-06-27 22:18 UTC, BobobUnicorn commented on src/commands/reject.ts
> +async function sendPrivateFeedback (client: ProjectsClient, submission: Submission, content: string, reason: keyof typeof rejectionTemplates): Promise<boolean> {
also add the person who rejected the project to the thread

2022-06-27 22:18 UTC, BobobUnicorn commented on src/commands/utils.ts
> +    // TODO: revisit this once we have review threads implemented and stored in the DB
rm

2022-06-27 23:29 UTC, jtsshieh requested changes

2022-06-27 23:30 UTC, nullishamy commented on src/managers/commands.ts
> +    const guildCommands = new Map<Snowflake, any[]>()
My editor wasn't picking it up, it's stupid long, and i don't believe it's exported

2022-06-27 23:31 UTC, nullishamy commented on src/managers/commands.ts
> +      await cmd.onAutocomplete?.(this.client, interaction)
It's completely optional, not every command should implement it.

2022-06-27 23:32 UTC, jtsshieh commented on src/managers/commands.ts
> +    const guildCommands = new Map<Snowflake, any[]>()
Can't dispute the first two points, but I do believe it is exported: https://github.com/discordjs/discord-api-types/blob/6a813be83382e1606f1921cf00179fe1ce75c04f/rest/v10/interactions.ts#L64

2022-06-27 23:32 UTC, nullishamy commented on src/managers/commands.ts
> +      log.warn(`Got interaction for unknown command ${interaction.commandName}, was it registered in the commands array?`)
Imo error logs should be for exceptional circumstances, which this is not. The only reason this would happen is if we forget to add it to the array or we do not refresh commands after changing them.

2022-06-27 23:33 UTC, nullishamy commented on src/managers/commands.ts
> +    if (isStaff(interaction.member, this.client)) {
These permissions are / will be much more fine grained than the system discord offers.

2022-06-27 23:33 UTC, nullishamy commented on src/models/submission.ts
> +      const dataVotes = this._data.upvotes[isStaff ? 'staff' : 'veterans']
Only when we use the class accessor, this accesses the field directly.

2022-06-27 23:34 UTC, nullishamy commented on src/commands/edit.ts
> +        .addStringOption(submissionNameStringOption)
It's a lot of duplication if we do that, since all current commands use these 2 values, if I understand you correctly.

2022-06-27 23:35 UTC, jtsshieh commented on src/commands/edit.ts
> +        .addStringOption(submissionNameStringOption)
Got it. Didn't realize that both commands used these options.

2022-06-27 23:39 UTC, nullishamy commented on src/managers/commands.ts
> +    const guildCommands = new Map<Snowflake, any[]>()
It was suggested externally that we just compute the return type of the function, which I think would better suite what we are attempting to do. Thoughts?

```ts
ReturnType<SlashCommandBuilder['toJSON']>
```

2022-06-27 23:39 UTC, jtsshieh commented on src/managers/commands.ts
> +    const guildCommands = new Map<Snowflake, any[]>()
That would work a lot better for code readability.

2022-06-27 23:40 UTC, nullishamy commented on src/models/submission.ts
> +      const dataVotes = this._data.upvotes[isStaff ? 'staff' : 'veterans']
This *is* a problem, but because we arent actually mutating the fields of the object, it still works. This needs to be fixed though.

2022-06-27 23:41 UTC, nullishamy commented on src/models/submission.ts
> +      const dataVotes = this._data.upvotes[isStaff ? 'staff' : 'veterans']
Will resolve by using only the `Readonly` type, without freezing the object. This is fine because we are only using TS in this project.

2022-06-27 23:41 UTC, jtsshieh commented on src/models/submission.ts
> +      const dataVotes = this._data.upvotes[isStaff ? 'staff' : 'veterans']
Yeah I think I meant to link to a different line.

2022-06-28 11:13 UTC, nullishamy commented
I'm thinking that the UI/UX for the edit command is suboptimal, perhaps we could utilise embeds for readability there?

2022-06-29 00:32 UTC, BobobUnicorn requested changes

2022-06-29 00:32 UTC, BobobUnicorn commented on src/commands/reject.ts
> +      content: `CC <@${voter.id}> as rejector.`
do we actually want to expose this information?

2022-06-29 00:32 UTC, BobobUnicorn commented on src/events/messageReactionRemove.ts
>      // No need for a -1 check, we know it exists
rm comment

2022-06-29 00:32 UTC, BobobUnicorn commented on src/utils/processVote.ts
> +    // Add the user id to the removed reactions set so we dont process this reaction remove event accidentally
```suggestion
    // Add the user id to the removed reactions set so we don't process this reaction remove event accidentally
```

2022-06-29 10:03 UTC, nullishamy commented on src/commands/reject.ts
> +      content: `CC <@${voter.id}> as rejector.`
It was left as a review comment, and I don't think it's a bad thing to include. Previously, they would be privy to this info anyways.

2022-06-29 21:38 UTC, BobobUnicorn commented on src/commands/reject.ts
> +      content: `CC <@${voter.id}> as rejector.`
I think saying "rejector" explicitly isn't a great thing; perhaps "for additional feedback" if anything

2022-06-29 21:43 UTC, BobobUnicorn approved these changes

2022-06-29 22:01 UTC, jtsshieh approved these changes

2022-06-29 22:07 UTC, nullishamy commented on src/commands/edit.ts
> +  const type = interaction.options.getSubcommand(true) as 'name' | 'description' | 'source' | 'other'
Wasn't aware the default was true, looking at the types:

```ts
  public getSubcommand(required?: true): string;
  public getSubcommand(required: boolean): string | null;
```

I dont think the explicit nature of this hurts, it's good to be aware that this is required.

2022-06-29 22:10 UTC, jtsshieh commented on src/commands/edit.ts
> +  const type = interaction.options.getSubcommand(true) as 'name' | 'description' | 'source' | 'other'
Makes sense and I agree.

2022-06-29 22:32 UTC, merged