Pause project submission
TheCodingDen/projects-bot pull request #39
Opened 2020-10-29 18:42 UTC by robertmcodes

Add pausing for project submissions in case something is awaiting confirmation or changes.

2020-11-01 13:43 UTC, linuswillner requested changes
Attached: My catalogue of mostly whinging nitpicks. Some major bugbears in there, though.

2020-11-01 13:43 UTC, linuswillner commented on src/db/index.ts
> +  return { success: true, wasPaused: type === 'up', wasApproved: hasEnoughUpvotes, wasRejected: hasEnoughDownvotes, reason: '', project }
```suggestion
  return { success: true, wasPaused: state === 'enabled', wasApproved: hasEnoughUpvotes, wasRejected: hasEnoughDownvotes, reason: '', project }
```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionAdd.ts
The use of `reaction.emoji` appears to be growing to be significant, not only here but later in the function. Maybe something like this and use that instead?
```suggestion
const { emoji } = reaction

```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionAdd.ts
> +      reaction.emoji?.name === process.env.PAUSE_REACTION
See previous. Also, seems I had a past blunder here that slipped my mind, that optional chaining isn't necessary as `reaction.emoji` is guaranteed to exist.

```suggestion
    const isValidEmoji = emoji.id === process.env.UPVOTE_REACTION ||
      emoji.id === process.env.DOWNVOTE_REACTION ||
      emoji.name === process.env.PAUSE_REACTION
```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionAdd.ts
> +      const isPause = reaction.emoji.name === process.env.PAUSE_REACTION
See previous
```suggestion
      const isUpvote = emoji.id === process.env.UPVOTE_REACTION
      const isDownvote = emoji.id === process.env.DOWNVOTE_REACTION
      const isPause = emoji.name === process.env.PAUSE_REACTION
```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionAdd.ts
>        // Don't need to check anything more here as checks that the other emoji is a downvote are already performed upstream
This comment seems to now be lying, considering we have 3 conditions now.

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionAdd.ts
> +          : await adjustDownvotesForProject('add', id, member)
_Really_ not digging the double ternary here. Could we rework this to be a simple if-else ladder as a matter of readability?

Moreover, the `pause` function name and first parameter are now incorrect if my suggestions are applied, so remember to rename them too if you do apply them.

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionAdd.ts
> +      await showcase(input)
This block is affected by several suggestions around naming and interface location I make down the line for the `showcase` file. Just keep that in mind, in case you do apply them.

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionRemove.ts
```suggestion
const { emoji } = reaction

```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionRemove.ts
> +      reaction.emoji.name === process.env.PAUSE_REACTION
```suggestion
    const isValidEmoji = emoji.id === process.env.UPVOTE_REACTION ||
      emoji.id === process.env.DOWNVOTE_REACTION ||
      emoji.name === process.env.PAUSE_REACTION
```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionRemove.ts
> +      const isPause = reaction.emoji.name === process.env.PAUSE_REACTION
```suggestion
      const isUpvote = emoji.id === process.env.UPVOTE_REACTION
      const isDownvote = emoji.id === process.env.DOWNVOTE_REACTION
      const isPause = emoji.name === process.env.PAUSE_REACTION
```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionRemove.ts
> +          : await adjustDownvotesForProject('remove', id, member)
Again, this double ternary really grinds my readability gears. If-else ladder?

Moreover, if suggestions surrounding the `pause` function are approved, that function call needs reworking now as well.

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionRemove.ts
> +      log.info(`User ${user.id} (${user.tag}) removed their ${isUpvote ? 'upvote' : isPause ? 'pause' : 'downvote'} for project ${project.name} (ID ${project.id})`)
This is perhaps one of the best examples where double ternaries cause significant readability issues. I'm not exactly sure on how this could best be fixed, but all I do know is that it needs a rework.

Besides that, a terminology change might be in order if you applied some of my earlier changes (`pause` => `suspend`)

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionRemove.ts
>        // and a removal of a vote can never push a project beyond a positive threshold
Unless I'm mistaken, these comments appear to be lying now
```suggestion
```

2020-11-01 13:43 UTC, linuswillner commented on src/events/messageReactionRemove.ts
> +      await showcase(input)
This block is affected by several suggestions around naming and interface location I make down the line for the `showcase` file. Just keep that in mind, in case you do apply them.

2020-11-01 13:43 UTC, linuswillner commented on src/utils/hasEnoughVotes.ts
> +export default (type: 'up' | 'down', operation: 'add' | 'remove' | 'dry', voter: Discord.GuildMember, project: Project): boolean => {
What's the reason behind calling this "dry"? Would a more appropriate name be "suspend" or "pause", depending on which term you want to go with?

2020-11-01 13:43 UTC, linuswillner commented on src/utils/hasEnoughVotes.ts
> +      : project[type === 'up' ? 'upvotes' : 'downvotes'][isStaff ? 'staff' : 'veterans'] - 1
Double ternary again.

2020-11-01 13:43 UTC, linuswillner commented on src/utils/showcase.ts
> +}
Move this to `src/typings/interfaces` please. Furthermore, maybe consider renaming it to something a bit more precise. Same goes for this file; I'd prefer it be called "processProjectAction" or something along those lines that describes what it actually does. Please name the interface in conjunction with that potential change.

Not going to specifically nitpick this one later in this file just to save space, but just remember to rename your references if you do make that change.

2020-11-01 13:43 UTC, linuswillner commented on src/utils/showcase.ts
> +  const { success, reason, project } = result
I'm kind of meh about how you pass everything as one huge parameter and then have to destructure it to oblivion for it to make any sense. Maybe pass down the internal data and the data from Discord as separate parameters, that way the divide is clearer and you don't need to do as much of this mega-destructuring here?

2020-11-01 13:43 UTC, linuswillner commented on src/utils/showcase.ts
> +  if (isPause && !isUpvote && !isDownvote) {
This line is somewhat funny in its irony; the comment on L27 says that only one of these can be true at once per operation, yet you check for all of them anyway. This is unnecessary 😄 
```suggestion
  if (isPause) {
```

2020-11-01 13:43 UTC, linuswillner commented on src/utils/showcase.ts
> +    log.info(`Project ${project.name} (ID ${project.id}) was ${wasPaused ? 'paused' : 'resumed'} by **${user.tag}** (${user.id})`)
There appears to have been a bit of a mix-up here, considering the log appears to be trying to use Discord Markdown syntax despite obviously being sent into stdout. It could also use some wording improvements.
```suggestion
    log.info(`Voting on project ${project.name} (ID ${project.id}) was ${wasPaused ? 'suspended' : 'unsuspended'} by user ${user.id} (${user.tag})`)
```

2020-11-01 13:43 UTC, linuswillner commented on src/utils/showcase.ts
> +  if ((wasApproved || wasRejected) && !wasPaused) {
See previous about only one of these being true at any one time
```suggestion
  if (wasApproved || wasRejected) {
```

2020-11-01 13:43 UTC, linuswillner commented on src/utils/showcase.ts
> +  if (wasApproved && !wasPaused) {
See again my previous about only one of these being true at any one time
```suggestion
  if (wasApproved) {
```

2020-11-01 13:57 UTC, robertmcodes commented on src/utils/showcase.ts
> +  const { success, reason, project } = result
I agree that it got kind of messy. In go land, it is common to pass a struct. That definitely influenced my decision here. I will move the guild, channel, and user params out though.

2020-11-01 14:03 UTC, robertmcodes commented on src/utils/hasEnoughVotes.ts
> +export default (type: 'up' | 'down', operation: 'add' | 'remove' | 'dry', voter: Discord.GuildMember, project: Project): boolean => {
My reasoning was because I have previous used 'dry' and projects like k8s use 'dry run' as a way to say that it won't be applied.

2020-11-01 14:05 UTC, linuswillner commented on src/utils/hasEnoughVotes.ts
> +export default (type: 'up' | 'down', operation: 'add' | 'remove' | 'dry', voter: Discord.GuildMember, project: Project): boolean => {
Yeah, I got that reference, I'm just looking for a word that describes the fact that it will be counted but not actioned until voting is unsuspended, which is not what a dry run canonically is.

2020-11-01 14:25 UTC, robertmcodes commented on src/utils/showcase.ts
> +}
I don't think that it should be renamed because it is the projects "showcase". I have already moved the interfaces to the interface file, but I am hesitant to change the file name as it does end up posting to the showcase channel.

2020-11-01 14:42 UTC, robertmcodes commented on src/utils/hasEnoughVotes.ts
> +export default (type: 'up' | 'down', operation: 'add' | 'remove' | 'dry', voter: Discord.GuildMember, project: Project): boolean => {
`hasEnoughVotes('up','void' voter, project)`... that looks weird.

2020-11-01 14:50 UTC, linuswillner commented on src/utils/hasEnoughVotes.ts
> +export default (type: 'up' | 'down', operation: 'add' | 'remove' | 'dry', voter: Discord.GuildMember, project: Project): boolean => {
Yeah, you're right. I guess there truly isn't a better word for it.

2020-11-01 22:27 UTC, linuswillner requested changes
Just a few more things 👀

2020-11-01 22:27 UTC, linuswillner commented on src/events/messageReactionAdd.ts
> +      await showcase(dInput, input)
Minor nit: We're not in GoLand, so let's use descriptive variable names please.

Another thing: You don't appear to be catching errors you throw in the `showcase` function. You'll want to catch and log that.

```suggestion
      const discordInput: ShowcaseDiscordInput = {
        guild,
        channel,
        user,
        reaction
      }
      await showcase(discordInput, input)
```

2020-11-01 22:27 UTC, linuswillner commented on src/events/messageReactionRemove.ts
>        // Don't need to check anything more here as checks that the other emoji is a downvote are already performed upstream
Could just remove this now too
```suggestion
```

2020-11-01 22:27 UTC, linuswillner commented on src/events/messageReactionRemove.ts
> +      await showcase(dInput, input)
Descriptive variable names, please.

See also: My previous about uncaught error from the `showcase` function
```suggestion
      const discordInput: ShowcaseDiscordInput = {
        guild,
        channel,
        user,
        reaction
      }
      await showcase(discordInput, input)
```

2020-11-06 07:36 UTC, linuswillner approved these changes

2020-11-06 07:36 UTC, merged