feat: use modals for /edit command
TheCodingDen/projects-bot pull request #47
Opened 2022-07-21 22:55 UTC by nullishamy

Closes #42

2022-07-22 01:16 UTC, BobobUnicorn requested changes

2022-07-22 01:16 UTC, BobobUnicorn commented on src/managers/commands.ts
> +    }
```ts
const INTERACTION_HANDLER_MAPPING = [
  ['isCommand', 'handleCommand'],
  ['isAutocomplete', 'handleAutocomplete'],
  ['isModalSubmit', 'handleModalSubmit']
] as const

for (const [fn, handler] of INTERACTION_HANDLER_MAPPING) {
  if (interaction[fn]()) {
    await this[handler](interaction)
  }
}
```

2022-07-22 01:16 UTC, BobobUnicorn commented on src/managers/commands.ts
> +    const submission = await this.client.submissions.fetch(submissionId)
nit: submissionRes

2022-07-22 01:19 UTC, nullishamy commented on src/commands/edit.ts
> +      embeds: [embeds.privateSubmission(submission.toIncoming(), submission.author)]
Produces an `IncomingSubmissionData` object which is what this function requires. It's tedious to make such an object so it's a function. The function takes that type because it requires the data before we have formed a model.

2022-07-22 01:19 UTC, nullishamy commented on src/commands/edit.ts
> +    await interaction.reply({
We want to log when someone makes an edit, so this should be posted into the thread.

2022-07-22 01:21 UTC, BobobUnicorn commented on src/commands/edit.ts
> +      embeds: [embeds.privateSubmission(submission.toIncoming(), submission.author)]
add comment pls

2022-07-22 01:28 UTC, nullishamy commented on src/managers/commands.ts
> +    }
This raises a lot of type errors so cannot work safely.

2022-07-22 21:42 UTC, BobobUnicorn commented on src/commands/edit.ts
> +  const [,,type] = interaction.customId.split('|')
actually, better suggestion

one func to encapsulate the `.split` and return the correctly typed data

one func to encapsulate joining the data into the ID

2022-07-22 21:49 UTC, nullishamy commented on src/commands/edit.ts
> +  const [,,type] = interaction.customId.split('|')
this is going to be fixed with #55, so we will use that when it merges

2022-07-23 17:10 UTC, BobobUnicorn approved these changes

2022-07-23 17:15 UTC, merged