feat: rejection automation
TheCodingDen/projects-bot pull request #48
Opened 2022-07-21 23:42 UTC by nullishamy

Closes #41

2022-07-21 23:43 UTC, nullishamy commented
Still to do: drafting support within the bot.

2022-07-22 22:50 UTC, BobobUnicorn requested changes

2022-07-22 22:50 UTC, BobobUnicorn commented on prisma/schema.prisma
> +  id Int @default(autoincrement())
make the id generation consistent (cuid or uuid seem appropriate)

2022-07-22 22:50 UTC, BobobUnicorn commented on prisma/schema.prisma
> +  @@id([id, submissionId])
just id

2022-07-22 22:50 UTC, BobobUnicorn commented on src/commands/draft.ts
> +    const [,submissionId] = interaction.customId.split('|')
factor out the customId stuff

2022-07-22 22:50 UTC, BobobUnicorn commented on prisma/schema.prisma
> +model Draft {
also add timestamp for this draft

2022-07-22 22:50 UTC, BobobUnicorn commented on src/managers/submissions.ts
> +            id: 'desc'
order by timestamp

2022-07-22 22:50 UTC, BobobUnicorn commented on src/utils/actionVotes.ts
> +  let rejectionMessage = `<@${actioningVote.voter.id}>, please send the message belown to this thread:`
use template string pls thx <3

2022-07-22 22:50 UTC, BobobUnicorn commented on src/utils/actionVotes.ts
> +    .join(' ')
factor this bit out?

2022-07-22 22:50 UTC, BobobUnicorn commented on src/utils/actionVotes.ts
> +  // FIXME: change to private thread
fix

2022-07-22 22:50 UTC, BobobUnicorn commented on src/utils/actionVotes.ts
> +    type: 'GUILD_PUBLIC_THREAD'
idea: set it as a config env

2022-07-23 18:23 UTC, BobobUnicorn commented on src/utils/actionVotes.ts
> +  // Callers should check this
```suggestion
  // Callers should already have checked this
```

2022-07-23 18:28 UTC, BobobUnicorn approved these changes

2022-07-23 18:28 UTC, merged