Add license check to submissions
TheCodingDen/projects-bot pull request #75
Opened 2020-12-07 00:40 UTC by Quozlet

Currently only for GitHub submissions

2020-12-07 00:42 UTC, Quozlet commented
I haven't testing this as I just don't have all the config needed to actually start up the bot. I did test the GraphQL query though: https://developer.github.com/v4/explorer/

Response for a valid license is the SPDX id, otherwise the license field is null

2020-12-08 04:05 UTC, Quozlet commented
```js
const Discord = require('discord.js');
const { GraphQLClient, gql } = require('graphql-request');
const client = new Discord.Client();
const ghClient = new GraphQLClient('https://api.github.com/graphql')
ghClient.setHeader('Authorization', `bearer ${process.env.GITHUB_TOKEN}`)
client.once('ready', () => {
    console.log('Ready!');
});

client.on('message', async message => {
    if (!message.content.startsWith('?') || message.author.bot) return;
    try {
        const url = new URL(message.content.slice('?'.length).trim().split(' ').shift());
        const ghQuery = gql`
        query ($url: URI!) {
          resource(url: $url) {
            ... on Repository {
              licenseInfo {
                spdxId
              }
            }
          }
        }  
        `
        const licenseData = await ghClient.request(ghQuery, { url: url.toString() })
        message.channel.send(`Eligible? ${!!url.hostname.contains("github.com")} Valid license? ${JSON.stringify(licenseData)} says ${!!(licenseData?.resource?.licenseInfo)}`);
    } catch (e) {
        message.channel.send(`Error: ${e}`)
    }

});

client.login(process.env.DISCORD_TOKEN);
```
![ss](https://user-images.githubusercontent.com/25412088/101438334-0fa72300-390a-11eb-96f8-c36dbce64970.png)

2020-12-18 12:46 UTC, linuswillner requested changes
A few nits small nits here and there, and then there's a big one.

Why is the license checking logic in the DB controller? To me, it seems entirely unrelated to anything the `nedb` database does. Please split it into a separate file, perhaps something like `utils/licenseCheck.ts` would be apt.

Otherwise stellar work. 👍🏻

2020-12-18 12:46 UTC, linuswillner commented on src/db/index.ts
> +  return !!submission.links.source.includes('github.com')
Unnecessary boolean coercion
```suggestion
  return submission.links.source.includes('github.com')
```

2020-12-18 12:46 UTC, linuswillner commented on src/db/index.ts
> +  return !!(licenseData as GitHubLicenseData)?.resource?.licenseInfo
Would prefer a bit more block segmentation here for the sake of readability
```suggestion
  `
  
  const licenseData = await ghClient.request(ghQuery, { url: submission.links.source })
  
  return !!(licenseData as GitHubLicenseData)?.resource?.licenseInfo
```

2020-12-21 19:14 UTC, linuswillner commented
This seems otherwise good now, package.json apparently changed under your feet though. If you could just fix that, I'd be happy to merge this 👍🏻

2020-12-27 23:30 UTC, linuswillner approved these changes

2020-12-27 23:31 UTC, merged